/**
 * Created by User on 2/6/2017.
 */
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_CLEAR_ERROR = 'LOGIN_CLEAR_ERROR';
export const LOGIN_NEW_TOKEN = 'LOGIN_NEW_TOKEN';

export const SIGNUP_PENDING = 'SIGNUP_PENDING';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const SIGNUP_CLEAR_USER = 'SIGNUP_CLEAR_USER';

export const LINK_ADD_REQUEST = 'LINK_ADD_REQUEST';
export const LINK_ADD_SUCCESS = 'LINK_ADD_SUCCESS';
export const LINK_ADD_FAIL = 'LINK_ADD_FAIL';
export const LINK_CLEAR_ERROR = 'LINK_CLEAR_ERROR';
export const LINK_CLEAR_DATA = 'LINK_CLEAR_DATA';
export const LINK_GET_ALL_REQUEST = 'LINK_GET_ALL_REQUEST';
export const LINK_GET_ALL_SUCCESS = 'LINK_GET_ALL_SUCCESS';
export const LINK_GET_ALL_FAIL = 'LINK_GET_ALL_FAIL';

